-- =============================================================
-- TradingTool-3 — Full Schema
-- Run this in Supabase SQL editor on a clean database.
-- =============================================================

-- Stocks table
CREATE TABLE IF NOT EXISTS public.stocks (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol           TEXT NOT NULL,
    instrument_token BIGINT NOT NULL,
    company_name     TEXT NOT NULL,
    exchange         TEXT NOT NULL,
    description      TEXT,
    priority         INTEGER,
    created_at       TIMESTAMPTZ DEFAULT NOW(),
    updated_at       TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(symbol, exchange),
    UNIQUE(instrument_token)
);

-- Watchlists table
CREATE TABLE IF NOT EXISTS public.watchlists (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE,
    description TEXT,
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    updated_at  TIMESTAMPTZ DEFAULT NOW()
);

-- Watchlist-Stock junction table
CREATE TABLE IF NOT EXISTS public.watchlist_stocks (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    watchlist_id BIGINT NOT NULL REFERENCES public.watchlists(id) ON DELETE CASCADE,
    stock_id     BIGINT NOT NULL REFERENCES public.stocks(id) ON DELETE CASCADE,
    created_at   TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(watchlist_id, stock_id)
);

-- Tags table: centralised tag names (shared by stocks and watchlists)
CREATE TABLE IF NOT EXISTS public.tags (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Stock-Tag junction table
CREATE TABLE IF NOT EXISTS public.stock_tags (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id   BIGINT NOT NULL REFERENCES public.stocks(id) ON DELETE CASCADE,
    tag_id     BIGINT NOT NULL REFERENCES public.tags(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(stock_id, tag_id)
);

-- Watchlist-Tag junction table
CREATE TABLE IF NOT EXISTS public.watchlist_tags (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    watchlist_id BIGINT NOT NULL REFERENCES public.watchlists(id) ON DELETE CASCADE,
    tag_id       BIGINT NOT NULL REFERENCES public.tags(id) ON DELETE CASCADE,
    created_at   TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(watchlist_id, tag_id)
);

-- Stock notes: timestamped journal entries per stock (chat-style, immutable once pushed)
CREATE TABLE IF NOT EXISTS public.stock_notes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id   BIGINT NOT NULL REFERENCES public.stocks(id) ON DELETE CASCADE,
    content    TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- User layout: single-row JSON blob storing watchlist and stock ordering
-- id is always 1 — only one row ever exists.
CREATE TABLE IF NOT EXISTS public.user_layout (
    id          INT PRIMARY KEY DEFAULT 1,
    layout_data JSONB NOT NULL DEFAULT '{}',
    updated_at  TIMESTAMPTZ DEFAULT NOW()
);
INSERT INTO public.user_layout (id, layout_data) VALUES (1, '{}') ON CONFLICT (id) DO NOTHING;

-- Kite tokens: persists Kite Connect access tokens across service restarts
-- Only the latest row is used; older rows are kept for audit trail.
-- Tokens expire at 6:00 AM IST daily — the cron-job refreshes them via /kite/callback.
CREATE TABLE IF NOT EXISTS public.kite_tokens (
    id           SERIAL PRIMARY KEY,
    access_token TEXT        NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_stocks_symbol              ON public.stocks(symbol);
CREATE INDEX IF NOT EXISTS idx_stocks_instrument_token    ON public.stocks(instrument_token);
CREATE INDEX IF NOT EXISTS idx_stocks_exchange_symbol     ON public.stocks(exchange, symbol);
CREATE INDEX IF NOT EXISTS idx_stocks_created_at          ON public.stocks(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_watchlist_stocks_wl        ON public.watchlist_stocks(watchlist_id);
CREATE INDEX IF NOT EXISTS idx_watchlist_stocks_stock     ON public.watchlist_stocks(stock_id);
CREATE INDEX IF NOT EXISTS idx_watchlist_stocks_created   ON public.watchlist_stocks(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_tags_name                  ON public.tags(name);

CREATE INDEX IF NOT EXISTS idx_stock_tags_stock           ON public.stock_tags(stock_id);
CREATE INDEX IF NOT EXISTS idx_stock_tags_tag             ON public.stock_tags(tag_id);

CREATE INDEX IF NOT EXISTS idx_watchlist_tags_wl          ON public.watchlist_tags(watchlist_id);
CREATE INDEX IF NOT EXISTS idx_watchlist_tags_tag         ON public.watchlist_tags(tag_id);

CREATE INDEX IF NOT EXISTS idx_stock_notes_stock          ON public.stock_notes(stock_id);
CREATE INDEX IF NOT EXISTS idx_stock_notes_created        ON public.stock_notes(created_at DESC);

-- kite_tokens
CREATE INDEX IF NOT EXISTS idx_kite_tokens_created        ON public.kite_tokens(created_at DESC);

-- Trades: consolidated trade journal with FIFO consolidation
CREATE TABLE IF NOT EXISTS public.trades (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id            BIGINT NOT NULL REFERENCES public.stocks(id) ON DELETE CASCADE,
    nse_symbol          TEXT NOT NULL,
    quantity            INTEGER NOT NULL,
    avg_buy_price       NUMERIC(10,2) NOT NULL,
    today_low           NUMERIC(10,2),
    stop_loss_percent   NUMERIC(5,2) NOT NULL,
    stop_loss_price     NUMERIC(10,2) NOT NULL,
    notes               TEXT,
    trade_date          DATE NOT NULL,
    created_at          TIMESTAMPTZ DEFAULT NOW(),
    updated_at          TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_trades_stock_id          ON public.trades(stock_id);
CREATE INDEX IF NOT EXISTS idx_trades_stock_date        ON public.trades(stock_id, trade_date);
CREATE INDEX IF NOT EXISTS idx_trades_created_at        ON public.trades(created_at DESC);
