-- Stocks table: Individual stock details
CREATE TABLE IF NOT EXISTS public.stocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    instrument_token BIGINT NOT NULL,
    company_name TEXT NOT NULL,
    exchange TEXT NOT NULL,
    description TEXT,
    priority INTEGER,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(symbol, exchange),
    UNIQUE(instrument_token)
);

-- Backward-compatible column additions for existing environments
ALTER TABLE public.stocks
    ADD COLUMN IF NOT EXISTS description TEXT;

ALTER TABLE public.stocks
    ADD COLUMN IF NOT EXISTS priority INTEGER;

-- Watchlists table: Watchlist details
CREATE TABLE IF NOT EXISTS public.watchlists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Watchlist-Stock junction table: Maps stocks to watchlists
CREATE TABLE IF NOT EXISTS public.watchlist_stocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    watchlist_id BIGINT NOT NULL REFERENCES public.watchlists(id) ON DELETE CASCADE,
    stock_id BIGINT NOT NULL REFERENCES public.stocks(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(watchlist_id, stock_id)
);

-- Tags table: Centralized tag names
CREATE TABLE IF NOT EXISTS public.tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Stock-Tag junction table: Maps tags to stocks
CREATE TABLE IF NOT EXISTS public.stock_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id BIGINT NOT NULL REFERENCES public.stocks(id) ON DELETE CASCADE,
    tag_id BIGINT NOT NULL REFERENCES public.tags(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(stock_id, tag_id)
);

-- Watchlist-Tag junction table: Maps tags to watchlists
CREATE TABLE IF NOT EXISTS public.watchlist_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    watchlist_id BIGINT NOT NULL REFERENCES public.watchlists(id) ON DELETE CASCADE,
    tag_id BIGINT NOT NULL REFERENCES public.tags(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(watchlist_id, tag_id)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_stocks_symbol ON public.stocks(symbol);
CREATE INDEX IF NOT EXISTS idx_stocks_instrument_token ON public.stocks(instrument_token);
CREATE INDEX IF NOT EXISTS idx_watchlist_stocks_watchlist_id ON public.watchlist_stocks(watchlist_id);
CREATE INDEX IF NOT EXISTS idx_watchlist_stocks_stock_id ON public.watchlist_stocks(stock_id);
CREATE INDEX IF NOT EXISTS idx_tags_name ON public.tags(name);
CREATE INDEX IF NOT EXISTS idx_stock_tags_stock_id ON public.stock_tags(stock_id);
CREATE INDEX IF NOT EXISTS idx_stock_tags_tag_id ON public.stock_tags(tag_id);
CREATE INDEX IF NOT EXISTS idx_watchlist_tags_watchlist_id ON public.watchlist_tags(watchlist_id);
CREATE INDEX IF NOT EXISTS idx_watchlist_tags_tag_id ON public.watchlist_tags(tag_id);
