-- =================================================================
-- tables.sql
--
-- Description: Minimal v1 schema for watchlist feature.
-- =================================================================

-- Shared helper for updated_at columns.
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- 1) stocks
-- Master table for unique stock instruments.
CREATE TABLE IF NOT EXISTS public.stocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nse_symbol TEXT NOT NULL UNIQUE,
    company_name TEXT NOT NULL,
    groww_symbol TEXT,
    kite_symbol TEXT,
    description TEXT,
    rating SMALLINT CHECK (rating >= 1 AND rating <= 5),
    tags TEXT[] NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT stocks_nse_symbol_format_chk
        CHECK (nse_symbol ~ '^[A-Z0-9][A-Z0-9._-]{0,31}$')
);

COMMENT ON TABLE public.stocks IS 'Unique stock instruments keyed by NSE symbol.';
COMMENT ON COLUMN public.stocks.tags IS 'Simple v1 tags list; normalize into tag tables in v2 if needed.';


-- 2) watchlists
-- Named watchlists for a single user.
CREATE TABLE IF NOT EXISTS public.watchlists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT watchlists_name_nonempty_chk CHECK (length(trim(name)) > 0)
);

COMMENT ON TABLE public.watchlists IS 'Named stock collections.';


-- 3) watchlist_stocks
-- Many-to-many relation with optional per-watchlist notes.
CREATE TABLE IF NOT EXISTS public.watchlist_stocks (
    watchlist_id BIGINT NOT NULL REFERENCES public.watchlists(id) ON DELETE CASCADE,
    stock_id BIGINT NOT NULL REFERENCES public.stocks(id) ON DELETE CASCADE,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (watchlist_id, stock_id)
);

COMMENT ON TABLE public.watchlist_stocks IS 'Links stocks to watchlists.';


-- Triggers for updated_at.
DROP TRIGGER IF EXISTS trg_stocks_set_updated_at ON public.stocks;
CREATE TRIGGER trg_stocks_set_updated_at
BEFORE UPDATE ON public.stocks
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_watchlists_set_updated_at ON public.watchlists;
CREATE TRIGGER trg_watchlists_set_updated_at
BEFORE UPDATE ON public.watchlists
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();
