import { useState, useEffect } from "react";

// ─── Nifty LargeMidcap 250 universe (sample 250) ───────────────────────────
const UNIVERSE = [
  "RELIANCE","TCS","HDFCBANK","INFY","ICICIBANK","HINDUNILVR","ITC","SBIN","BHARTIARTL","KOTAKBANK",
  "LT","AXISBANK","ASIANPAINT","MARUTI","TITAN","SUNPHARMA","ULTRACEMCO","BAJFINANCE","NESTLEIND","WIPRO",
  "POWERGRID","NTPC","HCLTECH","TECHM","INDUSINDBK","DRREDDY","DIVISLAB","CIPLA","EICHERMOT","HEROMOTOCO",
  "BAJAJFINSV","TATACONSUM","BRITANNIA","APOLLOHOSP","ADANIENT","ADANIPORTS","COALINDIA","ONGC","BPCL","IOC",
  "GRASIM","JSWSTEEL","TATASTEEL","HINDALCO","VEDL","NMDC","SAIL","NATIONALUM","HINDCOPPER","MOIL",
  "PIDILITIND","BERGEPAINT","AKZOINDIA","KANSAINER","INDIGO","IRCTC","CONCOR","CESC","TATAPOWER","ADANIGREEN",
  "TORNTPOWER","NHPC","SJVN","RECLTD","PFC","IRFC","HUDCO","NBCC","MUTHOOTFIN","CHOLAFIN",
  "BAJAJHLDNG","LICHSGFIN","CANFINHOME","PNBHOUSING","AAVAS","PAGEIND","VGUARD","HAVELLS","POLYCAB","FINOLEX",
  "KEI","NETWORK18","JUBLFOOD","DEVYANI","WESTLIFE","DMART","TRENT","NYKAA","MARICO","DABUR",
  "GODREJCP","ZYDUSLIFE","MANKIND","ALKEM","LUPIN","AUROPHARMA","IPCALAB","NATCOPHARM","GRANULES","PFIZER",
  "KPITTECH","MPHASIS","LT